# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
   - index.md
   - about.md
   - cv.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

tyle: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

theme: jekyll-theme-console
plugins:
  - jekyll-seo-tag
